# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(a1ee77c1-41d5-4566-afe0-520c3068e486)'
    subscriptionId: 'a1ee77c1-41d5-4566-afe0-520c3068e486'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg_hd_poc'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/aabhimanyuDataEngineer/test_repo/main/azuredeploy.json'
    deploymentMode: 'Incremental'